# Generated by Django 6.0.7 on 2026-08-03 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medicines', to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_records', to='health_records.healthrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
